# -*- coding: utf-8 -*-
"""data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBv4HyZStHUTlRrY13-BCFiApczvDzII
"""

import os
import random
from shutil import copyfile
random.seed(42)
import matplotlib.pyplot as plt
from glob import glob
import numpy as np
from sklearn.utils import compute_class_weight
import json
import tensorflow as tf

def set_global_seeds(seed=42):
    """Sets all seeds for reproducible results."""
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    tf.keras.utils.set_random_seed(seed)
    # Make TensorFlow operations deterministic on GPU
    tf.config.experimental.enable_op_determinism()

set_global_seeds(42)

path = "data/plant_village"
classes = ["Tomato___healthy", "Tomato___Early_blight", "Tomato___Late_blight", "Tomato___Leaf_Mold",
           "Potato___healthy", "Potato___Early_blight", "Potato___Late_blight", "Pepper,_bell___healthy",
           "Pepper,_bell___Bacterial_spot", "Corn_(maize)___Common_rust_"]

train_folder = os.path.join(path, 'split/train/')
val_folder = os.path.join(path, 'split/val/')
test_folder = os.path.join(path, 'split/test/')

def create_folders(path):
  try:
    os.makedirs(path)
  except FileExistsError:
    pass

create_folders("outputs/augmentation_samples")

#Create train, validation and test folders each with a subfolders for each class
for i in classes:
  create_folders(train_folder+i)
  create_folders(val_folder+i)
  create_folders(test_folder+i)

def split_data(SOURCE, TRAINING, VALIDATION, TESTING, SPLIT_SIZE_TRN):
    files = []
    imgs_list = [filename for filename in os.listdir(SOURCE)]
    print(f"{SOURCE} size: {len(imgs_list)}")
    for filename in imgs_list:
        file = os.path.join(SOURCE,filename)
        if os.path.getsize(file) > 0:
            files.append(filename)
        else:
            print(filename + " is zero length, so ignoring.")

    training_length = int(len(files) * SPLIT_SIZE_TRN)
    validation_length = testing_length = int((len(files) - training_length)/2)
    shuffled_set = random.sample(files, len(files))
    training_set = shuffled_set[0:training_length]
    print(f"Train dataset size: {len(training_set)}")
    validation_set = shuffled_set[training_length:training_length+validation_length]
    print(f"Validation dataset size: {len(validation_set)}")
    testing_set = shuffled_set[training_length+validation_length:]
    print(f"Test dataset size: {len(testing_set)}")

    for filename in training_set:
        this_file = os.path.join(SOURCE,filename)
        destination = os.path.join(TRAINING, filename)
        copyfile(this_file, destination)
    print(f"Train dataset created with size: {len(os.listdir(TRAINING))}")

    for filename in validation_set:
        this_file = os.path.join(SOURCE,filename)
        destination = os.path.join(VALIDATION, filename)
        copyfile(this_file, destination)
    print(f"Validation dataset created with size: {len(os.listdir(VALIDATION))}")

    for filename in testing_set:
        this_file = os.path.join(SOURCE,filename)
        destination = os.path.join(TESTING, filename)
        copyfile(this_file, destination)
    print(f"Test dataset created with size: {len(os.listdir(TESTING))}")

def class_split(classes, split_size):
  for c in classes:
    SOURCE_DIR = os.path.join(path,c)
    TRAINING_DIR = os.path.join(path, 'split/train/', c)
    VALIDATION_DIR = os.path.join(path, 'split/val/', c)
    TESTING_DIR = os.path.join(path, 'split/test/', c)
    split_data(SOURCE_DIR, TRAINING_DIR, VALIDATION_DIR, TESTING_DIR, split_size)

#Split the data with ratio train: validation: test --> 0.7: 0.15: 0.15
class_split(classes, .7)

train_dir = "./data/plant_village/split/train"

class_counts = {}
for class_name in os.listdir(train_dir):
    class_path = os.path.join(train_dir, class_name)
    if os.path.isdir(class_path):
        # Count image files (e.g., .jpg, .png)
        num_images = len(glob(os.path.join(class_path, "*.*")))
        class_counts[class_name] = num_images

print(class_counts)

# Extract keys and values
names = list(class_counts.keys())
values = list(class_counts.values())

plt.bar(names, values)
plt.title('Train Dataset Class Counts')
plt.xticks(rotation='vertical')
plt.show()

# Define paths and get labels
data_dir = train_dir
# Assumes subfolders are class names
labels = classes

# Get list of ALL files labels to calculate frequency
all_file_labels = []
for label in labels:
    files = os.listdir(os.path.join(data_dir, label))
    all_file_labels.extend([label] * len(files))

# Compute weights
keys = np.unique(all_file_labels)
weights = compute_class_weight(class_weight='balanced', classes=keys, y=all_file_labels)

# Create Dictionary mapped to integer indices
int_class_weight_dict = {i: weight for i, weight in enumerate(weights)}
class_weight_dict = {label: weight for label, weight in zip(keys, weights)}

print(class_weight_dict)

# Extract keys and values
names = list(class_weight_dict.keys())
values = list(class_weight_dict.values())

plt.bar(names, values)
plt.title('Train Dataset Class Weights')
plt.xticks(rotation='vertical')
plt.show()

# Get sorted class names (this is the order the loader will use)
class_names = sorted(class_counts.keys())   # e.g., ['Corn___Common_rust', 'Pepper_bell___Bacterial_spot', ...]
name_to_index = {name: idx for idx, name in enumerate(class_names)}

print(class_names)

print(name_to_index)

# Save class weights
with open('data/class_weights.json', 'w') as f:
    json.dump(int_class_weight_dict, f)

# save the class names order
with open('data/class_names.json', 'w') as f:
    json.dump(class_names, f)

def get_augmentation_pipeline():
    return tf.keras.Sequential([
        tf.keras.layers.RandomFlip("horizontal"),
        tf.keras.layers.RandomRotation(0.15),
        tf.keras.layers.RandomBrightness(factor=0.2, value_range=(0.0, 1.0)),
        tf.keras.layers.RandomContrast(0.2),
        tf.keras.layers.RandomZoom(0.1)
    ])

# To call the pipeline
# from src.data_prep import get_augmentation_pipeline
# augmentation_layer = get_augmentation_pipeline()

# Load and convert image to tensor
def load_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, [224, 224])
    img = img / 255.0   # Normalize to [0,1]
    return img

augmentation = get_augmentation_pipeline()
sample_path = os.path.join(train_dir, class_names[1])
files = os.listdir(sample_path)[:3]
for file in files:
  image = load_image(os.path.join(sample_path,file))
  augmented_image = augmentation(tf.expand_dims(image, 0), training=True)
  plt.figure(figsize=(10, 5))
  plt.subplot(1, 2, 1)
  plt.title("Original")
  plt.imshow(image)
  plt.subplot(1, 2, 2)
  plt.title("Augmented")
  plt.imshow(augmented_image[0]) # Remove batch dimension for plotting
  plt.show()
  tf.keras.utils.save_img("outputs/augmentation_samples/aug_"+file+".png", augmented_image[0])