# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHMpW_6Qgijzsz0ZjZXt92ArDstNj_8B
"""

!git clone https://github.com/mariamalaa76/zar3y-crop-disease

"""# Step 1 — Load your trained model"""

import os
import sys
import json
import time
import numpy as np
import tensorflow as tf
from pathlib import Path

# --- Directory Configuration ---
# Point ROOT directly to your cloned repo workspace
ROOT = Path("/content/zar3y-crop-disease").resolve()

# Define structural paths based on project root
MODEL_IN     = ROOT / "models" / "best_model.keras"  # Updated extension based on your actual file format!
FLOAT_TFLITE = ROOT / "models" / "model_float.tflite"
INT8_TFLITE  = ROOT / "models" / "model_quantized.tflite"
DATA_DIR     = ROOT / "data" / "plant_village"
OUTPUT_JSON  = ROOT / "outputs" / "quantization_benchmark.json"

# Auto-create directories if they don't exist yet
MODEL_IN.parent.mkdir(parents=True, exist_ok=True)
OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)

# --- Hyperparameters & Metadata ---
IMG_SIZE    = 224
BATCH_SIZE  = 32
CALIB_COUNT = 200          # Images for INT8 calibration
BENCH_COUNT = 100          # Images for latency benchmark

CLASSES = [
    "Tomato___healthy",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Potato___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Pepper_bell___healthy",
    "Pepper_bell___Bacterial_spot",
    "Corn___Common_rust",
]

print(f"Project Setup Complete.")
print(f"Expecting images at: {DATA_DIR}")
print(f"Outputting benchmarks to: {OUTPUT_JSON}")

print("Loading model …")
# handles both .keras (ZIP) files saved with .h5 extension
try:
    model = tf.keras.models.load_model(str(MODEL_IN))
except Exception:
    # rename trick if extension confuses Keras
    import shutil, tempfile
    tmp = Path(tempfile.mktemp(suffix=".keras"))
    shutil.copy(MODEL_IN, tmp)
    model = tf.keras.models.load_model(str(tmp))
    tmp.unlink()

print(f"  Model loaded — {MODEL_IN.name}")

print(model.summary())

"""# 2. preprocessing"""

def preprocess(image_path):
    """Load image → float32 tensor ready for MobileNetV3."""
    raw   = tf.io.read_file(str(image_path))
    img   = tf.image.decode_jpeg(raw, channels=3)
    img   = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img   = tf.keras.applications.mobilenet_v3.preprocess_input(img)  # → [-1, 1]
    return img.numpy().astype(np.float32)

"""# 3. collect image paths from the TEST split file"""

SPLIT_DIR = DATA_DIR / "splits"

def load_split_paths(split_name: str):
    """Read paths + labels written by data_prep.py (one path per line)."""
    path_file  = SPLIT_DIR / f"{split_name}_paths.txt"
    label_file = SPLIT_DIR / f"{split_name}_labels.txt"

    if not path_file.exists():
        # fallback: walk the directory tree directly
        print(f"  Split file not found — scanning {DATA_DIR} directly …")
        paths, labels = [], []
        for idx, cls in enumerate(CLASSES):
            cls_dir = DATA_DIR / cls
            if not cls_dir.exists():
                continue
            for img_path in sorted(cls_dir.glob("*.jpg"))[:200]:
                paths.append(img_path)
                labels.append(idx)
        return paths, labels

    paths  = [Path(p.strip()) for p in path_file.read_text().splitlines()]
    labels = [int(l.strip()) for l in label_file.read_text().splitlines()]
    return paths, labels

print("Collecting image paths …")
test_paths, test_labels = load_split_paths("test")
train_paths, _          = load_split_paths("train")
print(f"  Test  images : {len(test_paths)}")
print(f"  Train images : {len(train_paths)}")

"""# 4. representative dataset"""

calib_paths = train_paths[:CALIB_COUNT]

def representative_dataset():
    for p in calib_paths:
        img = preprocess(p)
        yield [np.expand_dims(img, axis=0)]

"""# 5. save float TFLite baseline"""

print("\nConverting → float TFLite …")
conv_float = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_float = conv_float.convert()
FLOAT_TFLITE.write_bytes(tflite_float)
float_mb = FLOAT_TFLITE.stat().st_size / 1e6
print(f"  Float model : {float_mb:.2f} MB  →  {FLOAT_TFLITE}")

"""# 6. convert → INT8 TFLite"""

print("\nConverting → INT8 TFLite (calibrating on 200 images) …")
conv_int8 = tf.lite.TFLiteConverter.from_keras_model(model)
conv_int8.optimizations              = [tf.lite.Optimize.DEFAULT]
conv_int8.representative_dataset     = representative_dataset
conv_int8.target_spec.supported_ops  = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
conv_int8.inference_input_type       = tf.float32   # keep float I/O for simplicity
conv_int8.inference_output_type      = tf.float32
tflite_int8 = conv_int8.convert()
INT8_TFLITE.write_bytes(tflite_int8)
int8_mb = INT8_TFLITE.stat().st_size / 1e6
print(f"  INT8  model : {int8_mb:.2f} MB  →  {INT8_TFLITE}")
print(f"  Compression : {float_mb / int8_mb:.1f}×")

"""# 7. latency + accuracy benchmark"""

# print("\nConverting → INT8 TFLite (calibrating on 200 images) …")
# conv_int8 = tf.lite.TFLiteConverter.from_keras_model(model)
# conv_int8.optimizations              = [tf.lite.Optimize.DEFAULT]
# conv_int8.representative_dataset     = representative_dataset

# # ⬇️ Remove the INT8-only ops restriction — use SELECT_TF_OPS as fallback
# conv_int8.target_spec.supported_ops  = [
#     tf.lite.OpsSet.TFLITE_BUILTINS,        # standard TFLite ops
#     tf.lite.OpsSet.SELECT_TF_OPS           # fallback for unsupported ops
# ]
# # Keep float I/O — avoids the XNNPACK INT8 kernel issue
# conv_int8.inference_input_type       = tf.float32
# conv_int8.inference_output_type      = tf.float32

# tflite_int8 = conv_int8.convert()
# INT8_TFLITE.write_bytes(tflite_int8)
# int8_mb = INT8_TFLITE.stat().st_size / 1e6
# print(f"  INT8  model : {int8_mb:.2f} MB  →  {INT8_TFLITE}")

bench_paths  = test_paths[:BENCH_COUNT]
bench_labels = test_labels[:BENCH_COUNT]

import os
import json
import time
import numpy as np
import tensorflow as tf # Changed from ai_edge_litert.interpreter

def benchmark_tflite(model_path, image_paths, true_labels):
    # Initialize the engine backend using a robust configuration strategy
    try:
        # Attempt to initialize without special delegates first
        interp = tf.lite.Interpreter(model_path=str(model_path))
        interp.allocate_tensors()
    except RuntimeError as e:
        print(f"   ⚠️  Note: XNNPACK runtime error encountered for {model_path.name}. Retrying with experimental_delegates=[].")
        # If XNNPACK fails, try again with explicit delegate disabling
        interp = tf.lite.Interpreter(
            model_path=str(model_path),
            experimental_delegates=[]
        )
        interp.allocate_tensors()

    input_details = interp.get_input_details()[0]
    output_details = interp.get_output_details()[0]

    inp_idx = input_details["index"]
    out_idx = output_details["index"]

    latencies, preds = [], []
    for path in image_paths:
        img = np.expand_dims(preprocess(path), axis=0).astype(np.float32)

        # Scale inputs down to appropriate integer constraints if required
        if input_details["dtype"] == np.int8:
            scale, zero_point = input_details["quantization"]
            img = (img / scale + zero_point).astype(np.int8)

        interp.set_tensor(inp_idx, img)

        t0 = time.perf_counter()
        interp.invoke()
        latencies.append(time.perf_counter() - t0)

        out = interp.get_tensor(out_idx)

        # De-quantize outputs back into probability space before decoding
        if output_details["dtype"] == np.int8:
            out_scale, out_zero_point = output_details["quantization"]
            out = (out.astype(np.float32) - out_zero_point) * out_scale

        preds.append(int(np.argmax(out)))

    correct = sum(p == l for p, l in zip(preds, true_labels))
    return {
        "avg_latency_ms": round(float(np.mean(latencies)) * 1000, 2),
        "p95_latency_ms": round(float(np.percentile(latencies, 95)) * 1000, 2),
        "accuracy":       round(correct / len(true_labels), 4),
    }

# =====================================================================
# Execution Block: Run Benchmarks and Log Metrics
# =====================================================================
print(f"\nBenchmarking optimization metrics on {BENCH_COUNT} validation samples...")

print("  Processing performance metrics for baseline float model...")
float_stats = benchmark_tflite(FLOAT_TFLITE, bench_paths, bench_labels)

print("  Processing performance metrics for optimized INT8 model...")
try:
    int8_stats = benchmark_tflite(INT8_TFLITE, bench_paths, bench_labels)
except RuntimeError as e:
    print(f"   ❌  INT8 model benchmarking failed due to: {e}")
    # Assign placeholder values to prevent NameError in subsequent cells
    int8_stats = {
        "avg_latency_ms": -1.0,
        "p95_latency_ms": -1.0,
        "accuracy":       0.0,
    }

# Compute comparative metric metadata safely within the same execution scope
acc_drop = float_stats["accuracy"] - int8_stats["accuracy"]
float_mb = os.path.getsize(FLOAT_TFLITE) / 1e6
int8_mb  = os.path.getsize(INT8_TFLITE) / 1e6

print("✅ Statistical validation evaluation phase complete.")

"""# 8. save benchmark JSON"""

# Ensure output directories exist safely before initiating storage writing routines
OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)

# Compile structured JSON payload for serialization
benchmark = {
    "float_model": {
        "path"           : str(FLOAT_TFLITE.relative_to(ROOT)),
        "size_mb"        : round(float_mb, 3),
        "avg_latency_ms" : float_stats["avg_latency_ms"],
        "p95_latency_ms" : float_stats["p95_latency_ms"],
        "accuracy"       : float_stats["accuracy"],
    },
    "int8_model": {
        "path"           : str(INT8_TFLITE.relative_to(ROOT)),
        "size_mb"        : round(int8_mb, 3),
        "avg_latency_ms" : int8_stats["avg_latency_ms"],
        "p95_latency_ms" : int8_stats["p95_latency_ms"],
        "accuracy"       : int8_stats["accuracy"],
    },
    "compression_ratio_x" : round(float_mb / int8_mb, 2),
    "accuracy_drop"        : acc_drop,
    "latency_speedup_x"    : round(float_stats["avg_latency_ms"] / int8_stats["avg_latency_ms"], 2),
    "benchmark_images"     : BENCH_COUNT,
    "calibration_images"   : CALIB_COUNT,
    "passes_spec": {
        "3x_compression" : (float_mb / int8_mb) >= 3.0,
        "lt5pct_acc_drop": acc_drop < 0.05,
    }
}

# Serialize information layout structure securely to path targets
OUTPUT_JSON.write_text(json.dumps(benchmark, indent=2))
print(f"\n Optimization profiling report exported → {OUTPUT_JSON}")

"""# 9. print summary table"""

print("\n" + "="*52)
print(f"{'Metric':<28} {'Float':>10} {'INT8':>10}")
print("="*52)
print(f"{'Size (MB)':<28} {float_mb:>10.2f} {int8_mb:>10.2f}")
print(f"{'Avg latency (ms)':<28} {float_stats['avg_latency_ms']:>10.1f} {int8_stats['avg_latency_ms']:>10.1f}")
print(f"{'P95 latency (ms)':<28} {float_stats['p95_latency_ms']:>10.1f} {int8_stats['p95_latency_ms']:>10.1f}")
print(f"{'Accuracy (100 imgs)':<28} {float_stats['accuracy']:>10.4f} {int8_stats['accuracy']:>10.4f}")
print(f"{'Accuracy drop':<28} {acc_drop:>10.4f}")
print(f"{'Compression':<28} {float_mb/int8_mb:>9.1f}x")
print("="*52)
print(f"  3× compression? {benchmark['passes_spec']['3x_compression']}")
print(f"  <5% acc drop?   {benchmark['passes_spec']['lt5pct_acc_drop']}")

